namespace Multiplayer.Common.ChatCommands;

/// <summary>
/// The concrete command registry is generated by <c>ChatCommandRegistryGenerator</c>
/// from classes annotated with <c>[ChatCommand]</c>.
/// </summary>
/// <remarks>
/// This partial declaration exists so the generated registry has a stable source
/// location in the IDE. The generated half provides <c>Register</c>, creates each
/// built-in command, attaches generated argument parsers, and registers command
/// names and aliases with <see cref="ChatCommandManager"/>.
/// </remarks>
internal static partial class ChatCommandRegistry
{
    /// <summary>
    /// Registers all source-generated chat commands and aliases.
    /// </summary>
    public static partial void Register(ChatCommandManager manager, MultiplayerServer server);
}
