# Based on workflow from https://github.com/krafs/LevelUp

name: Validate Pull Request

env:
  SLN_PATH: Source/

permissions:
  contents: read

on:
  pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  builds:
    name: Builds (${{ matrix.os }}, ${{ matrix.configuration }}, .NET ${{ matrix.sdk }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]
        sdk: [global.json, 10.0.x]
      fail-fast: false
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up .NET (from global.json)
      if: matrix.sdk == 'global.json'
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        global-json-file: global.json
        cache: true
        cache-dependency-path: '**/*.csproj'
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: Set up .NET (override SDK)
      if: matrix.sdk != 'global.json'
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: ${{ matrix.sdk }}
        cache: true
        cache-dependency-path: '**/*.csproj'
      env:
        DOTNET_NOLOGO: true
        DOTNET_CLI_TELEMETRY_OPTOUT: true

    - name: Display SDK version
      run: dotnet --version

    - name: Restore dependencies
      run: dotnet restore ${{ env.SLN_PATH }}

    - name: Build
      run: dotnet build ${{ env.SLN_PATH }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Run tests
      run: dotnet test ${{ env.SLN_PATH }} --configuration ${{ matrix.configuration }} --no-restore --logger "trx;logfilename=TestResults.trx"

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.configuration }}-${{ matrix.sdk }}
        path: '**/TestResults/**'
        retention-days: 7
        if-no-files-found: error
